---
- hosts: slave
  become: true
  tasks:
    - name: execute always 
      command: echo "this is from always tag"
      tags:
        - always
    - name: Install apache
      yum:
        name: "httpd"
        state: "present"
      tags:
        - install
    - name: Deploy static website
      copy:
        src: files/index.html
        dest: /var/www/html/
      tags:
        - config
